version: '2'
services:
  web:
    container_name: wishlist-container
    build: 
      context: ./
      dockerfile: ./Dockerfile
    command: sh ./setup.sh
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/server
    links:
      - database

  database:
    container_name: wishlist-database
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=wishlist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - '5433:5432'
